### PR TITLE
Fix UG for link and find

### LINKED ISSUE #251: UG: mismatch in case choice for `link` command
As in the UG: 
> Format: `link <index1> <linkName> <index2>`

`linkName` should be `link-name` instead (we use kebab-case for fields in the UG)

### LINKED ISSUE #305: [PE-D][Tester B] Formatting error under Link Command in UG
Image

Image

`<>` characters need to be escaped "\\< \\>" or wrapped by backticks "\`\<\>\`"

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by denz-denz**
Closes #305 Closes #251

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/LinkCommand.java [hunk 1]
```diff
@@ -19,22 +19,22 @@
...
+ * Meaning: person at INDEX-FROM is the LINK-NAME of the person at INDEX-TO.
  */
 public class LinkCommand extends Command {
 
     public static final String COMMAND_WORD = "link";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Links two persons.\n"
-            + "Parameters: INDEX1 LINK_NAME INDEX2\n"
+            + "Parameters: INDEX-FROM LINK-NAME INDEX-TO\n"
             + "Example: " + COMMAND_WORD + " 1 lawyer 2";
```
Comment (mattcce) [inline src/main/java/seedu/address/logic/commands/LinkCommand.java]: Should follow the syntax grammar used in the UG.
